"and" @keyword
"as" @keyword
"async" @keyword
"await" @keyword
"break" @keyword
"const" @keyword
"continue" @keyword
"do" @keyword
"elif" @keyword
"else" @keyword
"enum" @keyword
"false" @keyword
"for" @keyword
"func" @keyword
"if" @keyword
"impl" @keyword
"in" @keyword
"!in" @keyword
"infix" @keyword
"init" @keyword
"loop" @keyword
"match" @keyword
"mod" @keyword
"move" @keyword
"mut" @keyword
"return" @keyword
"or" @keyword
"party" @keyword
"pri" @keyword
"pub" @keyword
"ref" @keyword
"self" @keyword
"static" @keyword
"struct" @keyword
"super" @keyword
"this" @keyword
"trait" @keyword
"true" @keyword
"type" @keyword
"union" @keyword
"unsafe" @keyword
"use" @keyword
"let" @keyword
"where" @keyword
"while" @keyword
"yield" @keyword

"--" @operator
"-" @operator
"-=" @operator
"->" @operator
"=" @operator
"!=" @operator
"*" @operator
"&" @operator
"&&" @operator
"+" @operator
"++" @operator
"+=" @operator
"<" @operator
"==" @operator
">" @operator
"||" @operator

"." @delimiter
";" @delimiter
